import type { JwtConfig } from "../../infrastructure/jwt/jwt-token.service";
import type { KeycloakConfig } from "../../infrastructure/keycloak/keycloak-auth.provider";
import type { EmailConfig } from "../../infrastructure/email/mailpit-email.sender";
import type { ITokenStore } from "../../domain/ports/token-store.port";

export interface AuthModuleOptions {
  /** Path to the keycloak-realm.json generated by `auth-cli init` */
  keycloakConfigPath?: string;

  /** Inline Keycloak config (alternative to keycloakConfigPath) */
  keycloak?: KeycloakConfig;

  /** JWT signing configuration */
  jwt: JwtConfig;

  /** Email sender configuration */
  email: EmailConfig;

  /** Token store implementation (required; use PrismaTokenStore, TypeORM, etc.) */
  tokenStore: ITokenStore;
}

export interface AuthModuleAsyncOptions {
  imports?: any[];
  inject?: any[];
  useFactory: (...args: any[]) => Promise<AuthModuleOptions> | AuthModuleOptions;
}
